In [1]:
import pandas as pd

import numpy as np

diabetes = pd.read_csv('data/diabetes_data.csv', sep=',')

In [2]:
dupl_diabetes = list(diabetes.columns)
mask = diabetes.duplicated(subset=dupl_diabetes)
diabetes_duplicated = diabetes[mask]
diabetes = diabetes.drop_duplicates(subset=dupl_diabetes)
diabetes.shape

(768, 10)

In [3]:
#список неинформативных признаков
low_information_cols = [] 

#цикл по всем столбцам
for col in diabetes.columns:
    #наибольшая относительная частота в признаке
    top_freq = diabetes[col].value_counts(normalize=True).max()
    #доля уникальных значений от размера признака
    nunique_ratio = diabetes[col].nunique() / diabetes[col].count()
    # сравниваем наибольшую частоту с порогом
    if top_freq > 0.95:
        low_information_cols.append(col)
    # сравниваем долю уникальных значений с порогом
    if nunique_ratio > 0.95:
        low_information_cols.append(col)
diabetes.drop(low_information_cols, axis=1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98,58,33,190,34.0,0.430,43,0
1,2,112,75,32,0,35.7,0.148,21,0
2,2,108,64,0,0,30.8,0.158,21,0
3,8,107,80,0,0,24.6,0.856,34,0
4,7,136,90,0,0,29.9,0.210,50,0
...,...,...,...,...,...,...,...,...,...
763,5,139,64,35,140,28.6,0.411,26,0
764,1,96,122,0,0,22.4,0.207,27,0
765,10,101,86,37,0,45.6,1.136,38,1
766,0,141,0,0,0,42.4,0.205,29,1
767,0,125,96,0,0,22.5,0.262,21,0

In [4]:
def np_nan(arg):
    if arg == 0:
        return np.nan
    else:
        return arg
diabetes['Glucose'] = diabetes['Glucose'].apply(np_nan)
diabetes['BloodPressure'] = diabetes['BloodPressure'].apply(np_nan)
diabetes['SkinThickness'] = diabetes['SkinThickness'].apply(np_nan)
diabetes['Insulin'] = diabetes['Insulin'].apply(np_nan)
diabetes['BMI'] = diabetes['BMI'].apply(np_nan)
insulin_nan = diabetes['Insulin'].isnull().mean()
print(round(insulin_nan, 2))
display(diabetes)

0.49

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Gender
0,6,98.0,58.0,33.0,190.0,34.0,0.430,43,0,Female
1,2,112.0,75.0,32.0,NaN,35.7,0.148,21,0,Female
2,2,108.0,64.0,NaN,NaN,30.8,0.158,21,0,Female
3,8,107.0,80.0,NaN,NaN,24.6,0.856,34,0,Female
4,7,136.0,90.0,NaN,NaN,29.9,0.210,50,0,Female
...,...,...,...,...,...,...,...,...,...,...
763,5,139.0,64.0,35.0,140.0,28.6,0.411,26,0,Female
764,1,96.0,122.0,NaN,NaN,22.4,0.207,27,0,Female
765,10,101.0,86.0,37.0,NaN,45.6,1.136,38,1,Female
766,0,141.0,NaN,NaN,NaN,42.4,0.205,29,1,Female
767,0,125.0,96.0,NaN,NaN,22.5,0.262,21,0,Female

In [5]:
thresh = diabetes.shape[0]*0.7
diabetes = diabetes.dropna(thresh=thresh, axis=1)
print(diabetes.shape[1])

9